export const supabaseUrl = "https://jntgyctampkjvwsfbpdj.supabase.co";
export const supabaseAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpudGd5Y3RhbXBranZ3c2ZicGRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxNzY4ODgsImV4cCI6MjA0OTc1Mjg4OH0.S6k1sJXhKZD_u8toVESbUw3RPn_1HZ7jeEHaA_YhAO4";
